plugins:
  group_invitation_enabled:
    default: true
    client: true
  group_invitation_inviter_min_trust_level:
    default: 2
    enum: "TrustLevelSetting"
  group_invitation_inviters_sum_min_trust_level:
    default: 4
  group_invitation_min_inviters:
    default: 2
  group_invitation_invitee_min_trust_level:
    default: 2
    enum: "TrustLevelSetting"
  group_invitation_automatic_admit:
    default: true
  group_invitation_reason_required:
    default: false
  group_invitation_maximum_invitations_per_period:
    default: 10
  group_invitation_invite_time_period:
    default: 30